spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.tawsif.ecommerce.notification.PaymentNotificationRequest

server:
  port: 8060